# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push content to gig-a-blog

on:
  push:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout gig-a-blog
      run: |
        git clone https://github.com/tgig/gigablog.git
        cd gigablog
        git remote add --fetch --track main --no-tags mikigit https://github.com/tgig/Miki.git
        git read-tree --prefix=content/ -u mikigit/main
        git add .
        git commit -am "Updated content from Miki"
        git push
