name: Push content to gig-a-blog

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
          repository: 'tgig/gigablog'
    - name: Make changes
      run: |
        date > generated.txt
    - name: Commit files
      run: |
        git config --local user.name tgig
        git config --local user.email tgiggy@gmail.com
        git add .
        git commit -am "generated"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        repository: 'tgig/gigablog'
        branch: 'main'
        github_token: ${{ secrets.API_TOKEN_GITHUB }}


