name: Push content to gig-a-blog

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
          repository: 'tgig/gigablog'
    - run: |
        date > generated.txt
        git add .
        git commit -am "generated"
        git push
