name: Push content to gig-a-blog

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Push MIKI/POSTS files to Gigablog
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        destination_repo: 'tgig/gigablog'
        destination_folder: 'content'
        user_email: tgiggy@gmail.com
        user_name: 'tgig'
        commit_message: "Moving files from MIKI to Gigablog"
        destination_branch: main
