name: Push content to gig-a-blog

on:
  push:
    branches: main

jobs:
  integrate:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout gig-a-blog
      uses: actions/checkout@v2
      with:
          repository: 'tgig/gigablog'
    - name: Read in new files
      run: |
        git remote add --fetch --track main --no-tags mikigit https://github.com/tgig/Miki.git
        git read-tree --prefix=content/ -u mikigit/main
        git add .
        git commit -am "Updated content from Miki"
        git push
