name: Push content to gig-a-blog

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pushes to another repository
      uses: dmnemec/copy_file_to_another_repo_action@v1.0.4
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: "MIKI"
        destination_repo: 'tgig/gigablog'
        destination_folder: 'content/miki'
        user_email: tgiggy@gmail.com
        user_name: 'tgig'
        commit_message: "Moving files from Miki to Gigablog"
        destination_branch: main
