name: Push content to gig-a-blog

on:
  push:
    branches: main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pushes to another repository
      uses: cpina/github-action-push-to-another-repository@master
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: 'miki/100 Miki'
        destination-github-username: 'tgig'
        destination-repository-name: 'gigablog'
        user-email: tgiggy@gmail.com
        target-branch: main
        commit-message: See ORIGIN_COMMIT
    - name: Test get variable exported by push-to-another-repository
      run: echo $DESTINATION_CLONED_DIRECTORY
